// lib/message-types.ts
// Shared interface definitions utilized across all execution contexts.

// -- SSE Stream Event Types --

/** Token usage data extracted from the 'message_start' Claude API event */
export interface InputTokenCount {
    event: 'input_count';
    inputTokens: number;
    cacheCreateTokens: number;
    cacheReadTokens: number;
    model: string;
}

/** Output token counts parsed from the 'message_delta' Claude API event */
export interface OutputTokenCount {
    event: 'output_count';
    outputTokens: number;
    stopReason: string | null;
}

/** Individual textual token blocks resolved during streams */
export interface TextChunk {
    event: 'text';
    text: string;
}

/** Native upstream errors injected into the SSE feed by the provider */
export interface StreamError {
    event: 'stream_error';
    error: unknown;
}

/** Aggregate type for all valid token batch events */
export type TokenEvent = InputTokenCount | OutputTokenCount | TextChunk | StreamError;

// -- Health State Synchronization --

/** Tracks SSE stream lifecycle phases to evaluate connection health */
export interface HealthState {
    chunksProcessed: number;
    sawMessageStart: boolean;
    sawContentBlock: boolean;
    stopReason: string | null;
}

// -- LCO_V1 postMessage Bridge Types --
// These types define the wire format for cross-world messaging between
// Room 1 (inject.ts) and Room 2 (content script). Every message must carry
// the namespace and session token for the 5-layer security check.

/** The namespace used to identify all LCO bridge messages. */
export const LCO_NAMESPACE = 'LCO_V1' as const;

/** Accumulated token data flushed every 200ms from the MAIN world decoder */
export interface TokenBatchPayload {
    namespace: typeof LCO_NAMESPACE;
    type: 'TOKEN_BATCH';
    token: string;             // session token generated by the content script
    platform: string;          // 'claude' | 'chatgpt' — inlined from document.currentScript.dataset
    inputTokens: number;
    outputTokens: number;
    model: string;
}

/** Fired once after the SSE stream fully terminates */
export interface StreamCompletePayload {
    namespace: typeof LCO_NAMESPACE;
    type: 'STREAM_COMPLETE';
    token: string;
    platform: string;
    inputTokens: number;
    outputTokens: number;
    model: string;
    stopReason: string | null;
}

/** Fired if a health check failure is detected mid-stream */
export interface StreamHealthBrokenPayload {
    namespace: typeof LCO_NAMESPACE;
    type: 'HEALTH_BROKEN';
    token: string;
    platform: string;
    message: string;
}

/** Fired when free/Pro usage cap details are received */
export interface MessageLimitPayload {
    namespace: typeof LCO_NAMESPACE;
    type: 'MESSAGE_LIMIT_UPDATE';
    token: string;
    platform: string;
    messageLimitUtilization: number;
}

/** Union of all valid bridge message types */
export type LcoBridgeMessage = TokenBatchPayload | StreamCompletePayload | StreamHealthBrokenPayload | MessageLimitPayload;

// -- Tab Storage Schema (chrome.storage.session) --

/** Per-tab state persisted in chrome.storage.session under key `tabState_{tabId}` */
export interface TabState {
    platform: string;
    model: string;
    inputTokens: number;
    outputTokens: number;
    stopReason: string | null;
    messageLimitUtilization?: number;
    updatedAt: number;   // Unix timestamp (ms) of last write
}

/** Running session cost totals, stored under key `sessionCost_{tabId}` */
export interface SessionCost {
    totalInputTokens: number;
    totalOutputTokens: number;
    requestCount: number;
    updatedAt: number;
}

// -- Background Script Message Types --
// Messages sent from Room 2 to Room 3 via chrome.runtime.sendMessage.

/** Tokenizer request — existing pipe from the SSE decoder (bypasses bridge security) */
export interface CountTokensMessage {
    type: 'COUNT_TOKENS';
    text: string;
}

/** Store a batch of token data for the given tab */
export interface StoreTokenBatchMessage {
    type: 'STORE_TOKEN_BATCH';
    platform: string;
    model: string;
    inputTokens: number;
    outputTokens: number;
    stopReason: string | null;
}

/** Store usage cap data for the given tab */
export interface StoreMessageLimitMessage {
    type: 'STORE_MESSAGE_LIMIT';
    platform: string;
    messageLimitUtilization: number;
}

/** Union of all valid messages the background script will handle */
export type BackgroundMessage = CountTokensMessage | StoreTokenBatchMessage | StoreMessageLimitMessage;
