// lib/message-types.ts
// Shared interface definitions for all three execution contexts.

// LCO_V1 postMessage Bridge Types
// Wire format for cross-world messaging between Room 1 (inject.ts) and
// Room 2 (content script). Every message carries the namespace and session
// token for the 5-layer security check.

/** The namespace used to identify all LCO bridge messages. */
export const LCO_NAMESPACE = 'LCO_V1' as const;

/** Accumulated token data flushed every 200ms from the MAIN world decoder */
export interface TokenBatchPayload {
    namespace: typeof LCO_NAMESPACE;
    type: 'TOKEN_BATCH';
    token: string;             // session token generated by the content script
    platform: string;          // 'claude' | 'chatgpt', set via document.currentScript.dataset
    inputTokens: number;
    outputTokens: number;
    model: string;
    /** Organization UUID extracted from the API URL. Used for account isolation. */
    organizationId?: string;
}

/** Fired once after the SSE stream fully terminates */
export interface StreamCompletePayload {
    namespace: typeof LCO_NAMESPACE;
    type: 'STREAM_COMPLETE';
    token: string;
    platform: string;
    inputTokens: number;
    outputTokens: number;
    model: string;
    stopReason: string | null;
    /** First meaningful line of the user's prompt, for Conversation DNA. */
    topicHint?: string;
    /** Character count of the user's prompt text. */
    promptLength?: number;
    /** True when the prompt contains fenced code blocks (triple-backtick delimiters). */
    hasCodeBlock?: boolean;
    /** True when the prompt is shorter than 50 characters (terse follow-up). */
    isShortFollowUp?: boolean;
    /** Organization UUID extracted from the API URL. Used for account isolation. */
    organizationId?: string;
}

/** Standardized reasons for a health check failure. */
export type HealthBrokenReason =
    | 'missing_sentinel'      // 10+ chunks processed but stream_start event never arrived
    | 'stream_timeout'        // watchdog detected 120s of silence on an active stream
    | 'incomplete_lifecycle'; // stream_start arrived but stream_end never did

/** Fired if a health check failure is detected mid-stream */
export interface StreamHealthBrokenPayload {
    namespace: typeof LCO_NAMESPACE;
    type: 'HEALTH_BROKEN';
    token: string;
    platform: string;
    reason: HealthBrokenReason;
    message: string;
}

/** Fired when a stream completes cleanly after a previous HEALTH_BROKEN */
export interface StreamHealthRecoveredPayload {
    namespace: typeof LCO_NAMESPACE;
    type: 'HEALTH_RECOVERED';
    token: string;
    platform: string;
    recoveredAt: number;
}

/** Fired when free/Pro usage cap details are received */
export interface MessageLimitPayload {
    namespace: typeof LCO_NAMESPACE;
    type: 'MESSAGE_LIMIT_UPDATE';
    token: string;
    platform: string;
    messageLimitUtilization: number;
}

/** Fired once per page load when the org ID is first detected from any API call. */
export interface OrganizationDetectedPayload {
    namespace: typeof LCO_NAMESPACE;
    type: 'ORGANIZATION_DETECTED';
    token: string;
    platform: string;
    organizationId: string;
}

/** Union of all valid bridge message types */
export type LcoBridgeMessage = TokenBatchPayload | StreamCompletePayload | StreamHealthBrokenPayload | StreamHealthRecoveredPayload | MessageLimitPayload | OrganizationDetectedPayload;

// Tab Storage Schema (chrome.storage.session)

/** Per-tab state persisted in chrome.storage.session under key `tabState_{tabId}` */
export interface TabState {
    platform: string;
    model: string;
    inputTokens: number;
    outputTokens: number;
    stopReason: string | null;
    messageLimitUtilization?: number;
    updatedAt: number;   // Unix timestamp (ms) of last write
}

/** Running session cost totals, stored under key `sessionCost_{tabId}` */
export interface SessionCost {
    totalInputTokens: number;
    totalOutputTokens: number;
    requestCount: number;
    estimatedCost?: number;  // USD; absent when all requests used an unknown model
    updatedAt: number;
}

// Background Script Message Types
// Sent from Room 2 to Room 3 via chrome.runtime.sendMessage.

/** Tokenizer request. Bypasses bridge security (Room 2 to Room 3 only). */
export interface CountTokensMessage {
    type: 'COUNT_TOKENS';
    text: string;
}

/** Store a batch of token data for the given tab */
export interface StoreTokenBatchMessage {
    type: 'STORE_TOKEN_BATCH';
    platform: string;
    model: string;
    inputTokens: number;
    outputTokens: number;
    stopReason: string | null;
}

/** Store usage cap data for the given tab */
export interface StoreMessageLimitMessage {
    type: 'STORE_MESSAGE_LIMIT';
    platform: string;
    messageLimitUtilization: number;
}

/** Record a completed turn for persistent conversation storage */
export interface RecordTurnMessage {
    type: 'RECORD_TURN';
    organizationId: string;
    conversationId: string;
    inputTokens: number;
    outputTokens: number;
    model: string;
    contextPct: number;
    cost: number | null;
    /** First meaningful line of user prompt, for Conversation DNA. */
    topicHint?: string;
    /**
     * 5-hour session utilization consumed by this turn, in percentage points.
     * null when before/after snapshots were unavailable (e.g. first load, session
     * reset mid-turn, or fetch failure). Non-optional so omission is a compile error.
     */
    deltaUtilization: number | null;
}

/** Mark a conversation as finalized (user navigated away or tab closed) */
export interface FinalizeConversationMessage {
    type: 'FINALIZE_CONVERSATION';
    organizationId: string;
    conversationId: string;
}

/** Fetch a conversation record from chrome.storage.local */
export interface GetConversationMessage {
    type: 'GET_CONVERSATION';
    organizationId: string;
    conversationId: string;
}

/**
 * Update the active conversation for this tab in session storage.
 * Sent on SPA navigation so the side panel dashboard refreshes immediately
 * without waiting for the first RECORD_TURN of the new conversation.
 * conversationId is null when navigating to /new (no active conversation).
 */
export interface SetActiveConvMessage {
    type: 'SET_ACTIVE_CONV';
    organizationId: string | null;
    conversationId: string | null;
}

/** Union of all valid messages the background script will handle */
export type BackgroundMessage =
    | CountTokensMessage
    | StoreTokenBatchMessage
    | StoreMessageLimitMessage
    | StoreUsageLimitsMessage
    | RecordTurnMessage
    | FinalizeConversationMessage
    | GetConversationMessage
    | SetActiveConvMessage;

/** Response returned by the background after STORE_TOKEN_BATCH */
export interface StoreTokenBatchResponse {
    ok: boolean;
    tabState?: TabState;
    sessionCost?: SessionCost;
}

// ── Usage Limits Types ────────────────────────────────────────────────────────
// Data from the Anthropic usage endpoint: /api/organizations/{orgId}/usage
// This is the same data shown on claude.ai/settings/limits.

/**
 * Raw usage window data as returned by the Anthropic usage endpoint.
 * Each window has a utilization percentage (0-100) and a reset timestamp.
 */
export interface UsageLimitWindow {
    /** Current utilization as a percentage (0-100). 0 = none used, 100 = fully exhausted. */
    utilization: number;
    /** ISO 8601 timestamp of when this window resets. E.g. "2026-04-07T01:00:01.321075+00:00" */
    resetsAt: string;
}

/**
 * Structured usage data fetched from /api/organizations/{orgId}/usage.
 * Stored as `usageLimits:{accountId}` in chrome.storage.local.
 * Overwritten on each fetch; not appended.
 */
export interface UsageLimitsData {
    /** 5-hour rolling session window. "Current session" on the Usage page. */
    fiveHour: UsageLimitWindow;
    /** 7-day rolling window. "Weekly limits" on the Usage page. */
    sevenDay: UsageLimitWindow;
    /** Unix ms timestamp of when this record was fetched. Used to detect stale data. */
    capturedAt: number;
}

/**
 * Zone classification for usage budget display.
 * Determined by the higher of session and weekly utilization.
 * comfortable: <50% | moderate: 50-74% | tight: 75-89% | critical: >=90%
 */
export type BudgetZone = 'comfortable' | 'moderate' | 'tight' | 'critical';

/**
 * Output of the Usage Budget Agent (lib/usage-budget.ts).
 * All derived from UsageLimitsData; no estimation, no velocity.
 * Every value is either exact (from the endpoint) or clearly labeled as unavailable.
 */
export interface UsageBudgetResult {
    /** Session utilization as a percentage (0-100). Matches Settings > Usage exactly. */
    sessionPct: number;
    /** Weekly utilization as a percentage (0-100). Matches Settings > Usage exactly. */
    weeklyPct: number;
    /** Minutes until the 5-hour session window resets. Floored at 0. Exact from timestamp. */
    sessionMinutesUntilReset: number;
    /** Human-readable weekly reset label. E.g. "Wed 9:00 AM". */
    weeklyResetLabel: string;
    /** Zone based on max(sessionPct, weeklyPct). Drives color coding in the UI. */
    zone: BudgetZone;
    /** One-liner for the card's primary text. E.g. "11% used; resets in 53 min". */
    statusLabel: string;
}

// ── Usage Limits Bridge Messages ──────────────────────────────────────────────

/**
 * Posted from the content script to the background when usage data is fetched.
 * The content script fetches /api/organizations/{orgId}/usage directly
 * (same session cookies, no auth needed) and forwards the parsed result here.
 */
export interface StoreUsageLimitsMessage {
    type: 'STORE_USAGE_LIMITS';
    organizationId: string;
    fiveHourUtilization: number;
    fiveHourResetsAt: string;
    sevenDayUtilization: number;
    sevenDayResetsAt: string;
}
